baseURL       = "//royjara.xyz"
title         = "Roy Jara"
author        = "Roy Jara"
copyright     = "© 2022, Roy Jara"
paginate      = 4
languageCode  = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme         = "origin"
summarylength = 25

UglifyURLs = true
CanonifyURLs = true
[permalinks]
    blog = "/blog/:filename"
    portfolio = "/project/:filename"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.main]]
    name    = "About"
    url     = "/about"
    weight  = 1
  [[menu.main]]
    name    = "Get in touch"
    url     = "/contact"
    weight  = 2
  [[menu.main]]
    name    = "Theme?"
    url     = "/theme"
    weight  = 3

# used for tags:
[taxonomies]
  category = "cat"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

# Site Params
[params]
  description = "computers | art | music"
  featured = true
  cssonly = false
  # logo = "images/logo.png"
  dateFormat = "26-02-1994"

  [params.socials]
    instagram = "//www.instagram.com/evil_fft"
    github = "//github.com/roy-jara"
    medium= "//royjara.medium.com"